### ISSUE TITLE
HTML Skeleton- Team exercise

### ISSUE THREAD

**Issue by westgards** [mlhalbert/Random-Meal-Finder-UofM#3]
## Description

We will build the HTML together so we are familiar with the base code. This will drive the other work in CSS + JS

**Comment by por-chang** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>???</title>
    <link rel="stylesheet" >
    
  </head>
  <body>
    <header>
    <h> title of name</h1>
    </header>
    
    <div>
        <button class="btnheader" id="randon-meal">Suprise Me</button>
    </div>
    
    <div id ="main">
      
    </div>
    <div class="list">
            <div class="card">
              <div class="card-header">
                <h2>Search for a meal</h2>
              </div>
              <div class="card-body">
                
              </div>
                <button id="search-meal" class="btn">button</button>
              </div>
              <div class="food-allergy" class="allergy">button</div>
            </div>
          </div>
      
        </body>   
      
    </footer>
  </body>
</html>

**Comment by westgards** [comment]
Completed the mock up and skeleton
